In [5]:
import numpy as np
a=[
    256, 254, 254, 253,
    251 ,255, 240, 243,
    240 ,241, 256, 251,
    220, 231, 243, 246
]
a = np.array(a).reshape(4, 4)

a1 = np.copy(a)
for row in range(4):
    for col in range(0,3,2):
        x,y = a[row][col],a[row][col+1]
        l=np.floor((x+y)/2)
        h = abs(x-y)
        h1 = 2*h+1
        a1[row][col] = l+np.floor((h1+1)/2)
        a1[row][col+1]=h-np.floor(h1/2)
print("Original Array:\n", a)
print("Processed Array:\n", a1)

Original Array:
 [[256 254 254 253]
 [251 255 240 243]
 [240 241 256 251]
 [220 231 243 246]]
Processed Array:
 [[258   0 255   0]
 [258   0 245   0]
 [242   0 259   0]
 [237   0 248   0]]
